// Ctr/Cmd + Shift + P shortcut in VS Code for searching all things
// Step 1 : Install Paste JSON as Code extesntions
// Step 2 : Create a Typescript file with correct name
// Step 3: Go to your Json Data and COPY
// Step 4: Ctr/Cmd + Shift + P and search for Paste as Json from search bar
// Step 5: It will ask for Model name, provide the model name

// Generated by https://quicktype.io

export interface MovieCard {
    id:        number;
    title:     string;
    posterUrl: string;
    userId:     number;
    movieId:    number;
    reviewText: string;
    rating:     number;
}
// Generated by https://quicktype.io

